name: Build TI‑84 CE Program

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ce-programming/cedev:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Show toolchain version
        run: |
          echo "CEDEV prefix: $(cedev-config --prefix)"
          ez80-clang --version
          ez80-link --version

      - name: Build .8xp
        run: |
          make clean
          make

      - name: Upload TI‑84 CE artifact
        uses: actions/upload-artifact@v3
        with:
          name: passwordlock.8xp
          path: passwordlock.8xp
